CREATE USER ${DB_REPL_USER} REPLICATION LOGIN PASSWORD '${DB_REPL_PASSWORD}';

CREATE DATABASE ${DB_DATABASE};

\c ${DB_DATABASE};

CREATE TABLE IF NOT EXISTS bot_emails (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS bot_phonenumbers (
    id SERIAL PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL
);


--ALTER USER postgres WITH PASSWORD 'Qq12345';CREATE USER ${DB_REPL_USER} REPLICATION LOGIN PASSWORD '${DB_REPL_PASSWORD}';

